name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: 🚚 Enviar via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: "89.117.7.205"
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /domains/dreamsorcererstudios.com.br/public_html/
          # ADICIONE ESTA LINHA ABAIXO:
          protocol: ftp
